import { createContext, useCallback, useContext, useEffect, useMemo, useReducer, useState } from 'react'
import {
  createId,
  makeConversation,
  makeMessage,
  makeProject,
  makeLibraryItem,
  makeMemoryItem,
  makeProfile,
} from './types.js'

/**
 * MOCK / LOCAL DATA LAYER
 * ------------------------------------------------------------------
 * Everything in this file is a stand-in for a future backend. It persists
 * to localStorage only so the frontend architecture feels real to build
 * against — it is NOT a database and NOT an API client.
 *
 * Integration boundary: every exported function below (createConversation,
 * sendMessage, createProject, addConversationToProject, ...) is where a real
 * API / Supabase call will eventually replace the local state update. As
 * long as callers keep using these function names and shapes, swapping the
 * implementation later should not require changing component code.
 *
 * sendMessage() specifically is the AI-integration boundary: it currently
 * fakes a delayed assistant reply. Replace its body with a real request
 * when the model/master-prompt are ready — the pending -> complete/error
 * message lifecycle it drives is already what the UI expects.
 *
 * Library and Memory items are seeded once on first load purely so their
 * list/card UI has something to render. A real backend replaces these seeds
 * entirely — nothing here should be treated as real content, and Memory in
 * particular does NOT extract these automatically from conversations yet;
 * they exist only to demonstrate the view/edit/delete UI foundation.
 *
 * profile/settings: there is no authentication yet, so `profile` is not a
 * signed-in account — it's a single local record a person can fill in
 * (name/email), and `settings` is a set of local UI preferences. Both are
 * genuinely interactive (they persist to localStorage like everything else
 * here) but neither is backed by a real account or server.
 */

const STORAGE_KEY = 'ombre-mock-data-v1'

const SEED_LIBRARY_ITEMS = [
  {
    title: 'Startup validation notes',
    source: 'ombre',
    kind: 'note',
    preview: 'A structured summary generated from a General AI conversation.',
  },
  {
    title: 'Marketing angles — first draft',
    source: 'ombre',
    kind: 'document',
    preview: 'Three positioning angles worth testing, generated by Ombre.',
  },
]

const SEED_MEMORY_ITEMS = [
  {
    label: 'Preference',
    content: 'Prefers concise, direct answers over long explanations.',
  },
  {
    label: 'Project context',
    content: 'Working on Ombre, an AI mentorship platform, as the main project right now.',
  },
]

const DEFAULT_SETTINGS = {
  notifications: {
    email: true,
    inApp: true,
  },
  privacy: {
    saveHistory: true,
    rememberContext: true,
  },
  ai: {
    responseStyle: 'balanced', // 'concise' | 'balanced' | 'detailed'
    useNameInResponses: false,
    suggestMentors: true,
  },
}

function loadInitialState() {
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY)
    if (raw) {
      const parsed = JSON.parse(raw)
      return {
        conversations: {},
        projects: {},
        libraryItems: {},
        memoryItems: {},
        profile: null,
        settings: DEFAULT_SETTINGS,
        ...parsed,
      }
    }
  } catch {
    // ignore corrupt local data and fall back to empty state
  }
  return {
    conversations: {},
    projects: {},
    libraryItems: {},
    memoryItems: {},
    profile: null,
    settings: DEFAULT_SETTINGS,
  }
}

function reducer(state, action) {
  switch (action.type) {
    case 'CREATE_CONVERSATION': {
      const conversation = action.conversation
      return { ...state, conversations: { ...state.conversations, [conversation.id]: conversation } }
    }
    case 'ADD_MESSAGE': {
      const { conversationId, message } = action
      const conversation = state.conversations[conversationId]
      if (!conversation) return state
      const isFirstUserMessage = conversation.messages.length === 0 && message.role === 'user'
      const updated = {
        ...conversation,
        title: isFirstUserMessage ? message.content.slice(0, 60) : conversation.title,
        messages: [...conversation.messages, message],
        updatedAt: new Date().toISOString(),
      }
      return { ...state, conversations: { ...state.conversations, [conversationId]: updated } }
    }
    case 'UPDATE_MESSAGE': {
      const { conversationId, messageId, patch } = action
      const conversation = state.conversations[conversationId]
      if (!conversation) return state
      const messages = conversation.messages.map((m) => (m.id === messageId ? { ...m, ...patch } : m))
      return {
        ...state,
        conversations: {
          ...state.conversations,
          [conversationId]: { ...conversation, messages, updatedAt: new Date().toISOString() },
        },
      }
    }
    case 'CLEAR_CONVERSATIONS': {
      return { ...state, conversations: {} }
    }
    case 'CREATE_PROJECT': {
      const project = action.project
      return { ...state, projects: { ...state.projects, [project.id]: project } }
    }
    case 'ADD_CONVERSATION_TO_PROJECT': {
      const { conversationId, projectId } = action
      const project = state.projects[projectId]
      const conversation = state.conversations[conversationId]
      if (!project || !conversation) return state
      const conversationIds = project.conversationIds.includes(conversationId)
        ? project.conversationIds
        : [...project.conversationIds, conversationId]
      return {
        ...state,
        projects: { ...state.projects, [projectId]: { ...project, conversationIds } },
        conversations: {
          ...state.conversations,
          [conversationId]: { ...conversation, projectId },
        },
      }
    }
    case 'ADD_LIBRARY_ITEM': {
      const item = action.item
      return { ...state, libraryItems: { ...state.libraryItems, [item.id]: item } }
    }
    case 'SEED_LIBRARY_ITEMS_ONCE': {
      if (Object.keys(state.libraryItems).length > 0) return state
      const seeded = {}
      action.items.forEach((item) => {
        seeded[item.id] = item
      })
      return { ...state, libraryItems: seeded }
    }
    case 'ADD_MEMORY_ITEM': {
      const item = action.item
      return { ...state, memoryItems: { ...state.memoryItems, [item.id]: item } }
    }
    case 'UPDATE_MEMORY_ITEM': {
      const { id, patch } = action
      const item = state.memoryItems[id]
      if (!item) return state
      return {
        ...state,
        memoryItems: {
          ...state.memoryItems,
          [id]: { ...item, ...patch, updatedAt: new Date().toISOString() },
        },
      }
    }
    case 'DELETE_MEMORY_ITEM': {
      const { id } = action
      const next = { ...state.memoryItems }
      delete next[id]
      return { ...state, memoryItems: next }
    }
    case 'CLEAR_MEMORY': {
      return { ...state, memoryItems: {} }
    }
    case 'SEED_MEMORY_ITEMS_ONCE': {
      if (Object.keys(state.memoryItems).length > 0) return state
      const seeded = {}
      action.items.forEach((item) => {
        seeded[item.id] = item
      })
      return { ...state, memoryItems: seeded }
    }
    case 'SEED_PROFILE_ONCE': {
      if (state.profile) return state
      return { ...state, profile: action.profile }
    }
    case 'UPDATE_PROFILE': {
      return { ...state, profile: { ...state.profile, ...action.patch } }
    }
    case 'UPDATE_SETTINGS': {
      return { ...state, settings: { ...state.settings, ...action.patch } }
    }
    default:
      return state
  }
}

const OmbreDataContext = createContext(null)

export function OmbreDataProvider({ children }) {
  const [state, dispatch] = useReducer(reducer, undefined, loadInitialState)

  // Theme lives here (rather than in AppShell) so both the sidebar and the
  // Settings page can read and change the same value.
  const [theme, setTheme] = useState(() => {
    const stored = window.localStorage.getItem('ombre-theme')
    if (stored) return stored
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
  })
  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme)
    window.localStorage.setItem('ombre-theme', theme)
  }, [theme])
  const toggleTheme = useCallback(() => setTheme((t) => (t === 'dark' ? 'light' : 'dark')), [])

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state))
  }, [state])

  // Seed Library/Memory items and the local profile once, on first ever
  // load, so their UI has something to render. See the SEED_* data above.
  useEffect(() => {
    dispatch({
      type: 'SEED_LIBRARY_ITEMS_ONCE',
      items: SEED_LIBRARY_ITEMS.map((item) => makeLibraryItem(item)),
    })
    dispatch({
      type: 'SEED_MEMORY_ITEMS_ONCE',
      items: SEED_MEMORY_ITEMS.map((item) => makeMemoryItem(item)),
    })
    dispatch({ type: 'SEED_PROFILE_ONCE', profile: makeProfile() })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const createConversation = useCallback((opts) => {
    const conversation = makeConversation(opts)
    dispatch({ type: 'CREATE_CONVERSATION', conversation })
    return conversation.id
  }, [])

  const getConversation = useCallback((id) => state.conversations[id] ?? null, [state.conversations])

  const listConversations = useCallback(
    () => Object.values(state.conversations).sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : -1)),
    [state.conversations]
  )

  const clearAllConversations = useCallback(() => {
    dispatch({ type: 'CLEAR_CONVERSATIONS' })
  }, [])

  // MOCK reply generator. Replace with a real API call — see file header.
  const generateMockReply = useCallback((conversationId, userText, messageId) => {
    const delay = 700 + Math.random() * 700
    window.setTimeout(() => {
      if (userText.trim().toLowerCase() === 'error') {
        dispatch({
          type: 'UPDATE_MESSAGE',
          conversationId,
          messageId,
          patch: { status: 'error', content: '' },
        })
        return
      }
      dispatch({
        type: 'UPDATE_MESSAGE',
        conversationId,
        messageId,
        patch: {
          status: 'complete',
          content:
            'This is a placeholder response — Ombre isn\u2019t connected to a reasoning model yet. Once the General AI integration is in place, this is where a real answer will appear.',
        },
      })
    }, delay)
  }, [])

  const sendMessage = useCallback(
    (conversationId, text) => {
      const userMessage = makeMessage({ conversationId, role: 'user', content: text, status: 'complete' })
      dispatch({ type: 'ADD_MESSAGE', conversationId, message: userMessage })

      const assistantMessage = makeMessage({
        conversationId,
        role: 'assistant',
        content: '',
        status: 'pending',
      })
      dispatch({ type: 'ADD_MESSAGE', conversationId, message: assistantMessage })
      generateMockReply(conversationId, text, assistantMessage.id)
    },
    [generateMockReply]
  )

  const retryMessage = useCallback(
    (conversationId, messageId) => {
      dispatch({ type: 'UPDATE_MESSAGE', conversationId, messageId, patch: { status: 'pending' } })
      const conversation = state.conversations[conversationId]
      const lastUser = [...(conversation?.messages ?? [])].reverse().find((m) => m.role === 'user')
      generateMockReply(conversationId, lastUser?.content ?? '', messageId)
    },
    [generateMockReply, state.conversations]
  )

  const createProject = useCallback((name, description) => {
    const project = makeProject({ name, description })
    dispatch({ type: 'CREATE_PROJECT', project })
    return project.id
  }, [])

  const getProject = useCallback((id) => state.projects[id] ?? null, [state.projects])

  const addConversationToProject = useCallback((conversationId, projectId) => {
    dispatch({ type: 'ADD_CONVERSATION_TO_PROJECT', conversationId, projectId })
  }, [])

  const listProjects = useCallback(
    () => Object.values(state.projects).sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1)),
    [state.projects]
  )

  const listConversationsForProject = useCallback(
    (projectId) => {
      const project = state.projects[projectId]
      if (!project) return []
      return project.conversationIds
        .map((id) => state.conversations[id])
        .filter(Boolean)
        .sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : -1))
    },
    [state.projects, state.conversations]
  )

  const listLibraryItems = useCallback(
    (filter = 'all') => {
      const items = Object.values(state.libraryItems)
      const filtered =
        filter === 'all' ? items : items.filter((item) => item.source === filter)
      return filtered.sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1))
    },
    [state.libraryItems]
  )

  const listMemoryItems = useCallback(
    () => Object.values(state.memoryItems).sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : -1)),
    [state.memoryItems]
  )

  const createMemoryItem = useCallback((label, content) => {
    const item = makeMemoryItem({ label, content })
    dispatch({ type: 'ADD_MEMORY_ITEM', item })
    return item.id
  }, [])

  const updateMemoryItem = useCallback((id, patch) => {
    dispatch({ type: 'UPDATE_MEMORY_ITEM', id, patch })
  }, [])

  const deleteMemoryItem = useCallback((id) => {
    dispatch({ type: 'DELETE_MEMORY_ITEM', id })
  }, [])

  const clearAllMemory = useCallback(() => {
    dispatch({ type: 'CLEAR_MEMORY' })
  }, [])

  const getProfile = useCallback(() => state.profile, [state.profile])

  const updateProfile = useCallback((patch) => {
    dispatch({ type: 'UPDATE_PROFILE', patch })
  }, [])

  const getSettings = useCallback(() => state.settings, [state.settings])

  const updateSettings = useCallback((patch) => {
    dispatch({ type: 'UPDATE_SETTINGS', patch })
  }, [])

  const value = useMemo(
    () => ({
      theme,
      toggleTheme,
      createConversation,
      getConversation,
      listConversations,
      clearAllConversations,
      sendMessage,
      retryMessage,
      createProject,
      getProject,
      addConversationToProject,
      listProjects,
      listConversationsForProject,
      listLibraryItems,
      listMemoryItems,
      createMemoryItem,
      updateMemoryItem,
      deleteMemoryItem,
      clearAllMemory,
      getProfile,
      updateProfile,
      getSettings,
      updateSettings,
    }),
    [
      theme,
      toggleTheme,
      createConversation,
      getConversation,
      listConversations,
      clearAllConversations,
      sendMessage,
      retryMessage,
      createProject,
      getProject,
      addConversationToProject,
      listProjects,
      listConversationsForProject,
      listLibraryItems,
      listMemoryItems,
      createMemoryItem,
      updateMemoryItem,
      deleteMemoryItem,
      clearAllMemory,
      getProfile,
      updateProfile,
      getSettings,
      updateSettings,
    ]
  )

  return <OmbreDataContext.Provider value={value}>{children}</OmbreDataContext.Provider>
}

export function useOmbreData() {
  const ctx = useContext(OmbreDataContext)
  if (!ctx) throw new Error('useOmbreData must be used within OmbreDataProvider')
  return ctx
}

export { createId }
