import PageContainer from '../layout/PageContainer.jsx'

export default function Library() {
  return (
    <PageContainer
      title="Library"
      description="This workspace hasn't been built yet. Library will hold everything sent by you and everything generated by Ombre, connectable to any Project."
    />
  )
}
